ARG TAG=1.0

FROM fabriziocaf/lumen:$TAG

COPY ./source /var/www/

USER root

RUN cp .env.example .env \
    && set -xe \
    && composer global require "hirak/prestissimo" \
    && composer install --no-suggest --no-interaction --prefer-dist --optimize-autoloader \
    && composer dump-autoload --optimize --classmap-authoritative

USER www-data