#!/bin/bash

set -eE -o functrace

failure() {
  local lineno=$1
  local msg=$2
  echo "Failed at $lineno: $msg"
}
trap 'failure ${LINENO} "$BASH_COMMAND"' ERR

set -o pipefail
set -o nounset

main(){
  nginx_config
  
	nginx -c /etc/nginx/nginx.conf
	php-fpm
}

main "$@"
