#!/bin/bash

set -eE -o functrace

failure() {
  local lineno=$1
  local msg=$2
  echo "Failed at $lineno: $msg"
}
trap 'failure ${LINENO} "$BASH_COMMAND"' ERR

set -o pipefail
set -o nounset

main(){
	local HTTP_CONF=/etc/nginx/sites-available/http

	if [ ! -f $HTTP_CONF ] ; then
	  exit 1
	fi

	#PID dir
 	mkdir -p /run/nginx

	local SERVER_NAME="${DOMAIN} www.${DOMAIN}"
	sed -i "s/%SERVERNAME%/${SERVER_NAME}/g" $HTTP_CONF
	sed -i "s/%WORKDIRPATH%/${WORKDIRPATH//\//\\\/}/g" $HTTP_CONF

	if [ ! -d /etc/nginx/sites-enabled ] ; then
	  mkdir -p /etc/nginx/sites-enabled
	fi	
	if [ -L /etc/nginx/sites-enabled/default ] ; then
	  rm /etc/nginx/sites-enabled/default
	fi
	ln -s $HTTP_CONF /etc/nginx/sites-enabled/http.conf

	chown -R $WORKDIR_USER:$WORKDIR_GROUP /var/log/nginx
	chown -R $WORKDIR_USER:$WORKDIR_GROUP /var/lib/nginx
}

main "$@"
