#!/bin/bash

set -eE -o functrace

failure() {
  local lineno=$1
  local msg=$2
  echo "Failed at $lineno: $msg"
}
trap 'failure ${LINENO} "$BASH_COMMAND"' ERR

set -o pipefail
set -o nounset

main(){
	openssl req -x509 -nodes -new -sha256 -days 1024 -newkey rsa:2048 -keyout ${APPNAME}.key -out ${APPNAME}.pem -subj "/C=US/CN=${DOMAIN}"
	openssl x509 -outform pem -in ${APPNAME}.pem -out ${APPNAME}.crt
	
	local _cert_path="/etc/cert/${APPNAME}"

	mkdir -p $_cert_path

	mv ${APPNAME}.key $_cert_path/private.pem
	mv ${APPNAME}.crt $_cert_path/fullchain.pem
	rm -f ${APPNAME}.pem

	chmod 770 $_cert_path
	chown -R ${WORKDIR_USER}:${WORKDIR_GROUP} $_cert_path
}

main "$@"
