name: QA - Docker build

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]


env:
  ENVIRONMENT: qa
  APPNAME: test
  DOMAIN: locahost
  WORKDIR_USER: www-data
  WORKDIR_GROUP: www-data
  WORKDIRPATH: /var/www/test

jobs:
  test-docker:
    name: Build docker
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push - app image
        uses: docker/build-push-action@v2
        with:
          file: docker/php55/Dockerfile
          context: .
          push: false
          tags: latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          target: ${{ env.ENVIRONMENT }}

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache